# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_person_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='management.Event'),
        ),
    ]
