# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170423_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
        migrations.AddField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='management.Event'),
        ),
    ]
